//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointmentTab
    {
        public decimal apId { get; set; }
        public string apCode { get; set; }
        public string apName { get; set; }
        public Nullable<System.DateTime> apDate { get; set; }
        public Nullable<System.TimeSpan> apTime { get; set; }
        public string apNote { get; set; }
        public Nullable<decimal> paId { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual patientsTab patientsTab { get; set; }
    }
}
