//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int Branch_Num { get; set; }
        public string Branch_Name { get; set; }
        public string Address { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
