//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cash()
        {
            this.servicesRequestTab = new HashSet<servicesRequestTab>();
            this.testrRequesTab = new HashSet<testrRequesTab>();
        }
    
        public int Cash_Num { get; set; }
        public Nullable<int> Branch_Num { get; set; }
        public string Cash_Name { get; set; }
        public int Acc_Num { get; set; }
        public Nullable<int> Coin_Num { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicesRequestTab> servicesRequestTab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<testrRequesTab> testrRequesTab { get; set; }
    }
}
