//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coin()
        {
            this.servicesRequestTab = new HashSet<servicesRequestTab>();
            this.testrRequesTab = new HashSet<testrRequesTab>();
        }
    
        public int Coin_Num { get; set; }
        public string Coin_Name { get; set; }
        public string Symbol { get; set; }
        public Nullable<double> Coin_Price { get; set; }
        public string Coin_Type { get; set; }
        public Nullable<double> Coin_Max { get; set; }
        public Nullable<double> Coin_Min { get; set; }
        public string Coin_Sub { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicesRequestTab> servicesRequestTab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<testrRequesTab> testrRequesTab { get; set; }
    }
}
