//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class companySuplierDragTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public companySuplierDragTab()
        {
            this.dragTab = new HashSet<dragTab>();
        }
    
        public decimal comsId { get; set; }
        public string comsCode { get; set; }
        public string comsName { get; set; }
        public Nullable<int> comsMobile1 { get; set; }
        public Nullable<int> comsMobile2 { get; set; }
        public string comsAddress { get; set; }
        public string comsNote { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dragTab> dragTab { get; set; }
    }
}
