//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constriant_Affect
    {
        public int id { get; set; }
        public int Cons_Num { get; set; }
        public int Acc_Num { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Cridit { get; set; }
        public string Note { get; set; }
        public Nullable<double> Change_Coin { get; set; }
        public Nullable<int> Coin_Affect { get; set; }
        public Nullable<int> Cost_Centers_Num { get; set; }
    
        public virtual Constriant Constriant { get; set; }
    }
}
