//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constriant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Constriant()
        {
            this.Constriant_Affect = new HashSet<Constriant_Affect>();
        }
    
        public int Cons_Num { get; set; }
        public double Mony { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Operation_Num { get; set; }
        public string Cons_Type { get; set; }
        public Nullable<int> Coin_Num { get; set; }
        public string Is_Round { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Constriant_Affect> Constriant_Affect { get; set; }
    }
}
