//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class diagnoseTab
    {
        public decimal diId { get; set; }
        public string diCode { get; set; }
        public string diName { get; set; }
        public string diDate { get; set; }
        public string diTime { get; set; }
        public Nullable<decimal> viId { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
