//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctorsTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doctorsTab()
        {
            this.visitTab = new HashSet<visitTab>();
        }
    
        public decimal doId { get; set; }
        public string doCode { get; set; }
        public string doNameE { get; set; }
        public string doNameA { get; set; }
        public string doSex { get; set; }
        public string doBrithday { get; set; }
        public Nullable<int> doAge { get; set; }
        public Nullable<int> doMobile { get; set; }
        public string doAddress { get; set; }
        public byte[] doImg { get; set; }
        public string doCountry { get; set; }
        public string doCity { get; set; }
        public string doSpecil { get; set; }
        public string doQual { get; set; }
        public string doType { get; set; }
        public string doState { get; set; }
        public Nullable<decimal> clId { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual clinicTab clinicTab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visitTab> visitTab { get; set; }
    }
}
