//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class doseTab
    {
        public decimal doseId { get; set; }
        public string doseCode { get; set; }
        public string doseName { get; set; }
        public string doseQty { get; set; }
        public string doseTime { get; set; }
        public string doseSize { get; set; }
        public string doseUse { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
