//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class dragTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dragTab()
        {
            this.prescriptionTab = new HashSet<prescriptionTab>();
        }
    
        public decimal drId { get; set; }
        public string drCode { get; set; }
        public string drName { get; set; }
        public string drSname { get; set; }
        public string drNote { get; set; }
        public Nullable<decimal> sciId { get; set; }
        public Nullable<decimal> acId { get; set; }
        public Nullable<decimal> grdrId { get; set; }
        public Nullable<decimal> sfId { get; set; }
        public Nullable<decimal> comsId { get; set; }
        public Nullable<int> header0 { get; set; }
        public Nullable<int> header1 { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual activeMaterialTab activeMaterialTab { get; set; }
        public virtual companySuplierDragTab companySuplierDragTab { get; set; }
        public virtual groupDragTab groupDragTab { get; set; }
        public virtual scientificNameDragTab scientificNameDragTab { get; set; }
        public virtual shapeFarmacy shapeFarmacy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prescriptionTab> prescriptionTab { get; set; }
    }
}
