//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospitalCenterTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hospitalCenterTab()
        {
            this.clinicTab = new HashSet<clinicTab>();
        }
    
        public decimal hoId { get; set; }
        public string hoCode { get; set; }
        public string hoNameE { get; set; }
        public string hoNameA { get; set; }
        public Nullable<int> hoMobile1 { get; set; }
        public Nullable<int> hoMobile2 { get; set; }
        public string hoAddressE { get; set; }
        public string hoAddressA { get; set; }
        public Nullable<int> hoFix { get; set; }
        public byte[] hoImg { get; set; }
        public string hoNote { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clinicTab> clinicTab { get; set; }
    }
}
