//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipeTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recipeTab()
        {
            this.prescriptionTab = new HashSet<prescriptionTab>();
        }
    
        public decimal reId { get; set; }
        public string reCode { get; set; }
        public string reDate { get; set; }
        public string reTime { get; set; }
        public string reNote { get; set; }
        public Nullable<decimal> viId { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prescriptionTab> prescriptionTab { get; set; }
        public virtual visitTab visitTab { get; set; }
    }
}
