//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class resultTestTab
    {
        public decimal rtId { get; set; }
        public Nullable<decimal> itId { get; set; }
        public Nullable<decimal> trId { get; set; }
        public string result { get; set; }
        public string resultType { get; set; }
        public string rtNote { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual testItemTab testItemTab { get; set; }
        public virtual testrRequesTab testrRequesTab { get; set; }
    }
}
