//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class samplesTab
    {
        public decimal saId { get; set; }
        public string saCode { get; set; }
        public string saName { get; set; }
        public string saAmount { get; set; }
        public string saDate { get; set; }
        public string saTime { get; set; }
        public string saNote { get; set; }
        public Nullable<decimal> trId { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual testrRequesTab testrRequesTab { get; set; }
    }
}
