//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class serviecsTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public serviecsTab()
        {
            this.servicesLestTab = new HashSet<servicesLestTab>();
        }
    
        public decimal seId { get; set; }
        public string seCode { get; set; }
        public string seName { get; set; }
        public string seType { get; set; }
        public Nullable<decimal> sePrice { get; set; }
        public string seNote { get; set; }
        public Nullable<decimal> ACC_Num { get; set; }
<<<<<<< HEAD
        public Nullable<decimal> rateIn { get; set; }
        public Nullable<decimal> rateOut { get; set; }
        public Nullable<bool> isDeleted { get; set; }
=======
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<decimal> rateIn { get; set; }
        public Nullable<decimal> rateOut { get; set; }
>>>>>>> e6a6e25e17389587885aa1b30dd1c49071cf2971
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicesLestTab> servicesLestTab { get; set; }
    }
}
