//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicesLestTab
    {
        public decimal slId { get; set; }
        public Nullable<decimal> seId { get; set; }
        public Nullable<decimal> srId { get; set; }
        public string slnote { get; set; }
        public Nullable<double> slPrice { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual servicesRequestTab servicesRequestTab { get; set; }
        public virtual serviecsTab serviecsTab { get; set; }
    }
}
