//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicesRequestTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servicesRequestTab()
        {
            this.servicesLestTab = new HashSet<servicesLestTab>();
        }
    
        public decimal srId { get; set; }
        public string srCode { get; set; }
        public string srDate { get; set; }
        public string srManual { get; set; }
        public Nullable<decimal> srDiscount { get; set; }
        public Nullable<decimal> valueAdded { get; set; }
        public Nullable<int> Coin_Num { get; set; }
        public Nullable<int> Cash_Num { get; set; }
        public Nullable<decimal> viId { get; set; }
        public string methodPayment { get; set; }
        public Nullable<decimal> Coin_change { get; set; }
        public string state { get; set; }
        public Nullable<int> cons_Num { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Cash Cash { get; set; }
        public virtual Coin Coin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicesLestTab> servicesLestTab { get; set; }
        public virtual visitTab visitTab { get; set; }
    }
}
