//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Options
    {
        public int Id { get; set; }
        public string Options_Num { get; set; }
        public string Options_Name { get; set; }
        public string Options { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
