//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class testItemTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public testItemTab()
        {
            this.resultTestTab = new HashSet<resultTestTab>();
        }
    
        public decimal itId { get; set; }
        public string itCode { get; set; }
        public string itName { get; set; }
        public string itSname { get; set; }
        public string maxValue { get; set; }
        public string minValue { get; set; }
        public string unitName { get; set; }
        public Nullable<decimal> itPrice { get; set; }
        public string qty { get; set; }
        public Nullable<decimal> teId { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resultTestTab> resultTestTab { get; set; }
        public virtual testTab testTab { get; set; }
    }
}
