//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class testTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public testTab()
        {
            this.testItemTab = new HashSet<testItemTab>();
        }
    
        public decimal teId { get; set; }
        public string teCode { get; set; }
        public string teName { get; set; }
        public string teSname { get; set; }
        public string teNote { get; set; }
        public Nullable<decimal> grId { get; set; }
        public Nullable<decimal> rateIn { get; set; }
        public Nullable<decimal> rateOut { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual groupTestTab groupTestTab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<testItemTab> testItemTab { get; set; }
    }
}
