//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int User_Num { get; set; }
        public string Full_Name { get; set; }
        public string User_Login_Name { get; set; }
        public string User_Pass { get; set; }
        public string Permission_Level { get; set; }
        public string Address { get; set; }
        public string Phone_Num { get; set; }
        public Nullable<bool> Is_Admin { get; set; }
        public string Status { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
