//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class users1
    {
        public decimal userId { get; set; }
        public string userName { get; set; }
        public string Password { get; set; }
        public string confirmPassword { get; set; }
        public string userType { get; set; }
        public string userState { get; set; }
        public string email { get; set; }
        public Nullable<decimal> userIdentifier { get; set; }
    }
}
