//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenterManangement.DataModeView
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitTab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public visitTab()
        {
            this.previewTab = new HashSet<previewTab>();
            this.recipeTab = new HashSet<recipeTab>();
            this.servicesRequestTab = new HashSet<servicesRequestTab>();
            this.testrRequesTab = new HashSet<testrRequesTab>();
        }
    
        public decimal viId { get; set; }
        public string viCode { get; set; }
        public string viName { get; set; }
        public string viDate { get; set; }
        public string viTime { get; set; }
        public Nullable<decimal> paId { get; set; }
        public Nullable<decimal> apId { get; set; }
        public string viNote { get; set; }
        public Nullable<decimal> doId { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual doctorsTab doctorsTab { get; set; }
        public virtual patientsTab patientsTab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<previewTab> previewTab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipeTab> recipeTab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicesRequestTab> servicesRequestTab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<testrRequesTab> testrRequesTab { get; set; }
    }
}
